import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('minimax', {
  getObjectInfo: (url: string) => ipcRenderer.invoke('comfy:info', url),
  uploadImageData: (url: string, data: string) => ipcRenderer.invoke('comfy:upload-data', url, data),
  getOutputImage: (url: string, file: unknown) => ipcRenderer.invoke('comfy:output-image', url, file),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings: unknown) => ipcRenderer.invoke('settings:save', settings),
  chooseDirectory: (initialPath?: string) => ipcRenderer.invoke('dialog:directory', initialPath),
  chooseMedia: (type: 'image' | 'video' | 'audio') => ipcRenderer.invoke('dialog:media', type),
  scanModels: (settings: unknown) => ipcRenderer.invoke('models:scan', settings),
  getComfyStatus: (url: string) => ipcRenderer.invoke('comfy:status', url),
  submitPrompt: (url: string, prompt: unknown, clientId?: string) => ipcRenderer.invoke('comfy:submit', url, prompt, clientId),
  getQueue: (url: string) => ipcRenderer.invoke('comfy:queue', url),
  getHistory: (url: string, promptId: string) => ipcRenderer.invoke('comfy:history', url, promptId),
  cancelPrompt: (url: string, promptId: string) => ipcRenderer.invoke('comfy:cancel', url, promptId),
  uploadInput: (url: string, filePath: string) => ipcRenderer.invoke('comfy:upload', url, filePath),
  fileDataUrl: (filePath: string) => ipcRenderer.invoke('file:data-url', filePath),
  mediaUrl: (filePath: string) => ipcRenderer.invoke('file:media-url', filePath),
  extractVideoFrame: (source: string, position: number | 'last', outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:frame', source, position, outputDirectory, ffmpegPath),
  joinVideos: (clips: unknown[], outputDirectory: string, ffmpegPath: string) => ipcRenderer.invoke('video:join', clips, outputDirectory, ffmpegPath),
  showOutput: (outputPath: string) => ipcRenderer.invoke('shell:show-output', outputPath),
  findLatestOutput: (outputPath: string, since: number) => ipcRenderer.invoke('outputs:latest', outputPath, since),
  listOllamaModels: (url: string) => ipcRenderer.invoke('ollama:list', url),
  generateWithOllama: (url: string, model: string, prompt: string) => ipcRenderer.invoke('ollama:generate', url, model, prompt),
  generateStructuredWithOllama: (url: string, model: string, prompt: string, schema: Record<string, unknown>) => ipcRenderer.invoke('ollama:structured', url, model, prompt, schema),
  getLanStatus: () => ipcRenderer.invoke('lan:status'),
  rotateLanToken: () => ipcRenderer.invoke('lan:rotate-token'),
})
