/**
 * Camera path compiler — a pure, UI-free TypeScript port of the bruxosdovfx
 * "Camera H3" compiler from NyckM/3d-Camera-control-H3-Minimax (v19.1,
 * commit 846880de859959e801b2c506dc424bd5c8b5c6c4, Apache-2.0). Ported for
 * task ving89w with golden fidelity: compiled prompts, options and
 * storyboards are byte-identical to the Python output (verified against
 * fixtures generated BY the upstream source — scripts/test-camera.cjs).
 *
 * What it does: turns a camera trajectory (time 0..1 / azimuth° / elevation°
 * / distance× keyframes, anchored to the source image at the origin) into
 * engineered MiniMax-H3 prompts — Freeze Frame for FL2VA (first-frame
 * anchor), Motion Frame for Ref2VA (<Video 1> temporal reference) — plus
 * H3-Edit options, a storyboard document, and diagnostics. It compiles
 * PROMPTS, not camera embeddings: no geometric adapter exists upstream and
 * angular accuracy still depends on the model.
 *
 * Module map (Python origin in parens):
 * - constants.ts   widget tables + tuning constants (camera.py module level)
 * - types.ts       public data model
 * - parity.ts      CPython output parity (repr/:g/round/json.dumps)
 * - validatePath.ts trajectory validation + error taxonomy (validate_path)
 * - trajectoryMath.ts monotone PCHIP / smoothstep / linear sampling
 *                  (trajectory_math.py)
 * - cameraText.ts  aspect labels, parallax crossing counts, end view,
 *                  direction-mirror contract (camera.py helpers)
 * - planBuilder.ts the h3-camera-plan-v15 document (build_plan)
 * - coordinateAnchor.ts subject_box [L,T,W,H] anchor (coordinate_anchor)
 * - promptText.ts  plan → prompt text, six-section H3 format (plan_text)
 * - compileCamera.ts the Freeze compiler (compile_camera)
 * - motionFrame.ts Freeze/Motion node pipeline + <Video 1> rewrites +
 *                  17k+5 resampling (motion.py prepare_frames/motion_plan)
 * - diagnostics.ts read-only trajectory warnings (diagnostics.py)
 *
 * Deliberately NOT ported (deviations, flagged loudly):
 * - experimental.py prompt experiments (Article compact / numbers only) —
 *   upstream's OPEN QUESTION for A/B, owned by the benchmark harness task
 *   (Flux 0reycn4), not the compiler.
 * - build_h3world_actions / h3world_clause (H3-World action schedule) —
 *   defined but never called in the v19.1 compile path; revisit when the
 *   canvas-phase editor wants a latent-schedule preview.
 * - parallaxTravel / endView / directionContract ARE ported (the audited
 *   quirk vocabulary) but, exactly like upstream v19.1, are NOT injected
 *   into compiled prompts — build_plan carries a static parallax line.
 *
 * The camera EDITOR is out of scope by maintainer directive (Flux ving89w
 * directive b309fad7): it lands as a canvas-phase component consuming this
 * API. This library has zero UI, zero engine, zero browser dependencies.
 *
 * Licensing: Apache-2.0 source, faithful port with attribution; this repo is
 * AGPLv3 — see docs/PROVENANCE.md and docs/LICENSES.md §2.
 */
export type {
  CameraKeyframe, CameraPlan, CameraSegment, CameraStoryboard, CompileCameraParams, CompileMotionParams,
  CompileMotionResult, CompileResult, CoordinateAnchor, DiagnosticItem, DurationProfile, ElevationRangeKey,
  FrameMode, H3EditOptions, ImageShape, Interpolation, LoopClosureChoice, MinimaxFormat, MotionOptionsOverride,
  MotionResample, OrbitDirection, Pose, PromptDetail, RuntimeTask, StoryboardSource, SubjectFraming, UiLanguage,
} from './types'
export {
  DEFAULT_PATH, DIRECTED_FRAMES, DIRECTED_SETTLE, DIRECTED_TAIL_CANDIDATES, ELEVATION_RANGES, FPS, FRAMINGS,
  MINIMAX_FORMATS, MOTION_MODES, ORBIT_DIRECTIONS, PROFILES, PROMPT_DETAIL, RUNTIME_TASKS, VERTICAL_FOV,
} from './constants'
export { validatePath } from './validatePath'
export { AXES, interpolatePose } from './trajectoryMath'
export {
  aspectLabel, directionContract, endView, horizontalFov, imageAspect, parallaxTravel, reversalIndices,
} from './cameraText'
export { buildPlan } from './planBuilder'
export { coordinateAnchor } from './coordinateAnchor'
export { planText } from './promptText'
export { compileCamera } from './compileCamera'
export { compileMotion, motionFrameResample, motionPlan, motionText } from './motionFrame'
export { diagnosticText, reviewPath } from './diagnostics'
